### ISSUE TITLE
Git workflow for bundling releases

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/basic-cli#95]
@Hasnep has written [https://github.com/Hasnep/bundle-roc-library](https://github.com/Hasnep/bundle-roc-library) which can bundle roc libraries. 

Should we use this for `basic-cli`?

**Comment by Anton-4** [comment]
Because basic-cli is a platform, it needs to be built on macos x86, macos aarch64, linux aarch64 and linux x86. This can not be done with a github action because github currently has no aarch64 servers. We have a [workflow](https://github.com/roc-lang/roc/blob/main/.github/workflows/basic_cli_build_release.yml) in roc-lang/roc because that repo has all the required servers set up.
